#!/usr/bin/env bash
set -e

# Disable pager
export GH_PAGER=

if [ -z "$1" ]; then
  echo "Usage:"
  echo "gh workflow-log-cleaner [<workflow-id> | <workflow-name> | <filename>]"
  echo ""
  echo "Available workflows:"
  gh workflow list --json name --jq '.[].name | "- \(.)"'
  exit
fi

for id in $(gh run list --workflow "$1" --json databaseId --jq '.[].databaseId' --limit 10000); do
  echo "Deleting run ID: $id"
  gh run delete $id
done
