name: test
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  actions: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bats and Bats libs
        uses: bats-core/bats-action@2.0.0
      - name: Wait for the setup job to complete
        run: sleep 3
      - name: Run Bats tests
        run: bats --verbose-run --show-output-of-passing-tests gh-workflow-log-cleaner.bats
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
